packages:
  - packages/*
  - apps/cosmic-horizons-api
  - apps/cosmic-horizons-api-e2e
  - apps/cosmic-horizons-web
  - apps/cosmic-horizons-web-e2e
  - libs/shared/*

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver
